name: Presubmit
on: [push, pull_request]

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-20.04
    steps:
      - name: Install packages
        run: sudo apt install -y pocl-opencl-icd
      - uses: actions/checkout@v2
      - name: Build
        run: ./presubmit.sh
      - name: Run tests
        run: |
          ls -l
          cd build
          ls -l
          ls -l test_conformance
          ls -l test_conformance/api
          ls -l bin
          ./bin/test_api

